
osx_image: xcode11.3
language: swift
os: osx

xcode_workspace: AnyFormatKitSwiftUI.xcworkspace
xcode_scheme: 
  - AnyFormatKitSwiftUI

branches:
  only:
    - master
    - develop

notifications:
  email:
    recipients:
      - luximetr.notification@gmail.com
    on_success: always
    on_failure: always
