
osx_image: xcode12.2
language: swift
os: osx

xcode_workspace: AnyFormatKitSwiftUI.xcworkspace
xcode_scheme: 
  - AnyFormatKitSwiftUI

branches:
  only:
    - master
    - develop

notifications:
  email:
    recipients:
      - luximetr.notification@gmail.com
    on_success: always
    on_failure: always

before_install:
  - gem install cocoapods
  - gem update concurrent-ruby
  - pod setup

script:
  - pod install
  - pod lib lint
